### ISSUE TITLE
Action (as the example in README) is failing because of `length` undefined

### ISSUE THREAD

**Issue by David-Pena** [SethCohen/github-releases-to-discord#34]
This is the action:
```yml
on:
  release:
    types: [published]

jobs:
  github-releases-to-discord:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Github Releases To Discord
        uses: SethCohen/github-releases-to-discord@v1.15.1
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          color: '2105893'
          username: Release Changelog
          avatar_url: 'https://cdn.discordapp.com/avatars/487431320314576937/bd64361e4ba6313d561d54e78c9e7171.png'
          content: '||@everyone||'
          footer_title: Changelog
          footer_icon_url: 'https://cdn.discordapp.com/avatars/487431320314576937/bd64361e4ba6313d561d54e78c9e7171.png'
          footer_timestamp: true
          max_description: '4096'
          reduce_headings: true

```

This is the output

![image](https://github.com/user-attachments/assets/c7c3544e-5eb2-44f6-ae9c-bad2097df0be)

I'm not user whats failing, I'd apprecite any help 🙌
